/* config.h.  Hand-written for the espaudiocore build of libwavpack 5.9.0.
 *
 * Upstream WavPack is built with autotools (make + configure), so config.h is
 * generated by configure from configure.ac and is not part of the source tree.
 * This file reproduces what configure would produce for an ESP-IDF target
 * (xtensa-esp-elf / riscv32-esp-elf, newlib, GCC or esp-clang) and it is the
 * single place where libwavpack's compile-time features are selected here.
 *
 * configure.ac option / check     ->  macro below
 *   --enable-legacy               ->  ENABLE_LEGACY         (off, see below)
 *   --disable-dsd                 ->  ENABLE_DSD            (off, must stay off)
 *   --disable-threads             ->  ENABLE_THREADS        (off)
 *   --disable-asm                 ->  OPT_ASM_X86/X64/ARM   (never defined)
 *   AC_FUNC_FSEEKO                ->  HAVE_FSEEKO
 *   check for __builtin_clz/ctz   ->  HAVE___BUILTIN_CLZ / HAVE___BUILTIN_CTZ
 *   AC_DEFINE(LIBWAVPACK_*)       ->  comes from wavpack_version.h instead
 *
 * Every macro here is tested with #ifdef / #if defined() upstream, never with
 * #if <value>, so "#define X 0" means ENABLED, not disabled.  Turn a feature
 * off by commenting the line out, i.e. leaving it undefined.
 *
 * --- how these switches reach the rest of the library -----------------------
 *
 * Only unpack3.c, unpack3_open.c and unpack3_seek.c #include "config.h" (the
 * same is true upstream); every other module includes only wavpack_local.h.
 * The switches below therefore only affect those three files unless this header
 * is additionally force-included for all libwavpack sources, for example in
 * espaudiocore/CMakeLists.txt:
 *
 *     set(wavpack_srcs ...)                  # the .c files in lib/libwavpack
 *     set(wavpack_incs "${CMAKE_CURRENT_SOURCE_DIR}/lib/libwavpack")
 *     set_source_files_properties(${wavpack_srcs} PROPERTIES COMPILE_OPTIONS
 *         "-w;-Wno-error;-include;${wavpack_incs}/config.h")
 *
 * Use the absolute path exactly as shown: a -include file is looked up in the
 * compiler's working directory first and this component has several imported
 * libraries with a file called config.h (libflac, libopus, opusfile), so a bare
 * "-include;config.h" appended to the shared thirdparty_flags list could pick
 * up the wrong one.  The plain #include "config.h" inside the unpack3*.c files
 * needs no help: a quoted include searches the including file's directory
 * first, so it always finds this file.
 *
 * Without such a force-include, ENABLE_LEGACY would only produce dead code (the
 * pre-4.0 decoder would be linked, but open_utils.c would never call it because
 * it does not see the macro) and the HAVE___BUILTIN_* optimizations would
 * silently stay unused.  The equivalent alternative is to add
 * #include "config.h" at the top of wavpack_local.h, which touches the imported
 * source and is therefore not done here.
 *
 * --- notes for this decoder-only import ------------------------------------
 *
 * This directory holds the decoding half of libwavpack (no pack*.c, no
 * write_words.c), which is why ENABLE_DSD must stay undefined and why the
 * encoder-only modules extra1.c / extra2.c must not be built: they only define
 * the "extra mode" search used by pack.c, yet they reference init_words(),
 * nosend_word() and scan_word() from the missing write_words.c.  Nothing else
 * in this directory refers to them, so simply leaving those two files out of
 * the source list keeps the decoder self-contained.  (If they are compiled
 * anyway, the linker has to discard the unreferenced sections - e.g. with
 * -Wl,--gc-sections - otherwise it reports those three symbols as undefined.)
 */

/* Enable decoding of pre-4.0 (WavPack 1/2/3) files.
 * Requires unpack3.c + unpack3_open.c + unpack3_seek.c in the build (all three
 * are present in this directory) and adds about 15 KB of code with -Os on
 * xtensa (the decoder is ~33 KB without it and ~47 KB with it), so it is off by
 * default because files older than WavPack 4.0 are rare.
 * To enable, uncomment the #define below and add those three sources.  */
/* #undef ENABLE_LEGACY */

/* Enable DSD (dsdiff/dsf) support.
 * This directory contains no unpack_dsd.c / pack_dsd.c, so this must stay
 * undefined: open_utils.c, unpack_utils.c and unpack_seek.c all reference
 * unpack_dsd_samples() and decimate_dsd_*() and the link would fail.  Add
 * those two sources first if DSD playback is ever wanted.  */
/* #undef ENABLE_DSD */

/* Enable multithreaded unpacking of multichannel files.
 * Upstream implements this with pthreads; ESP-IDF's FreeRTOS POSIX layer could
 * satisfy it, but every worker needs its own WavpackStream plus a task stack,
 * so single threaded decoding is the better default on ESP32.  */
/* #undef ENABLE_THREADS */

/* Define if the C library provides fseeko/ftello.
 * ESP-IDF's newlib declares them in <stdio.h> (__POSIX_VISIBLE >= 200112,
 * visible with the default -std=gnu17), so open_filename.c can use them in
 * place of fseek/ftell.  Only the "open by filename" API
 * (WavpackOpenFileInput) is affected; the reader callback API is not.  */
#define HAVE_FSEEKO 1

/* Define if the compiler supports the __builtin_clz / __builtin_ctz builtins.
 * xtensa-esp-elf-gcc, riscv32-esp-elf-gcc and esp-clang all provide them:
 *   - HAVE___BUILTIN_CLZ lets count_bits() in wavpack_local.h use the hardware
 *     instruction (nsau on xtensa) instead of the 256-byte nbits_table.
 *   - HAVE___BUILTIN_CTZ selects the ctz version of the unary-code counter in
 *     read_words.c instead of the USE_NEXT8_OPTIMIZATION table version.
 * The guard keeps a host-side build with a non-GNU compiler working.  */
#if defined(__GNUC__) || defined(__clang__)
#define HAVE___BUILTIN_CLZ 1
#define HAVE___BUILTIN_CTZ 1
#endif

/* Library version macros: configure defines LIBWAVPACK_MAJOR / LIBWAVPACK_MINOR
 * / LIBWAVPACK_MICRO / LIBWAVPACK_VERSION_STRING here, but common_utils.c falls
 * back to wavpack_version.h when LIBWAVPACK_VERSION_STRING is missing, which
 * keeps the version number in exactly one place.  Deliberately not defined:
 *   LIBWAVPACK_MAJOR, LIBWAVPACK_MINOR, LIBWAVPACK_MICRO, LIBWAVPACK_VERSION_STRING
 */

/* Assembly optimizations (OPT_ASM_X86 / OPT_ASM_X64 / OPT_ASM_ARM): the
 * corresponding .S/.asm files are not part of this directory and only exist for
 * x86/x64/ARM, so none of these macros may be defined.  Leaving them undefined
 * also selects the portable log2buffer() and unpack implementations.  */

/* VERSION_OS, ENABLE_LIBICONV and AC_APPLE_UNIVERSAL_BUILD are only used by the
 * command line tools (cli/) and are not needed by the library.  */

/* Deliberately not defined here: _FILE_OFFSET_BITS=64 (AC_SYS_LARGEFILE).
 * It has to be set for the whole component, not only for the translation units
 * that happen to include this header, otherwise off_t and the FILE/struct
 * _reent layouts would differ between objects.  Add it in CMakeLists.txt when
 * files larger than 2 GB matter (it is also what makes fseeko/ftello 64-bit):
 *     target_compile_definitions(${COMPONENT_LIB} PRIVATE _FILE_OFFSET_BITS=64)
 */

/* BITSTREAM_SHORTS (16-bit bitstream access) is not configured here:
 * wavpack_local.h enables it automatically for little-endian targets from
 * __BYTE_ORDER__, so it is active on ESP32.  It reads the bitstream through
 * uint16_t pointers, which is safe because WavPack metadata payloads always
 * begin at an even offset inside an aligned block buffer.  */
